snowflake:
  type: snowflake
  account: EQHBCEY-AP74813
  database: ecommerce_db
  password: raskexbavxeKvesvy7
  role: ACCOUNTADMIN
  schema: analytics
  threads: 1
  type: snowflake
  user: JAYPATEL152251
  warehouse: COMPUTE_WH
  client_session_keep_alive: False